name: Deploy Secure Assistant
on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Inject Keys into Script
        run: |
          sed -i "s|INSERT_GEMINI_KEY_HERE|${{ secrets.GEMINI_API_KEY }}|g" script.js
          sed -i "s|INSERT_MURF_KEY_HERE|${{ secrets.MURF_API_KEY }}|g" script.js

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.' # This uploads your whole folder securely

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
